In [1]:
import pandas as pd

# Load the dataset into a pandas dataframe.
df = pd.read_csv("data/wikicorpus.csv")

# Report the number of sentences.
print('Number of training sentences: {:,}\n'.format(df.shape[0]))

# Display 10 random rows from the data.
df.sample(10)

Number of training sentences: 6,942

,id,category,length,text
5087,5087,Planung und Organisation,369,Unter operativer Planung versteht man eine Unt...
1994,1994,Herrscher nach Titel,307,Juri I. von Galizien (ukrainisch Ю́рій I Льво́...
3809,3809,Gemälde nach Jahrhundert,742,Venus und Mars ist ein Gemälde von Sandro Bott...
3543,3543,Album nach Typ,201,Footsteps in the Light ist das erste Kompilat...
3473,3473,Album nach Typ,474,Antennas to Hell ist ein Best-of-Album der US-...
1835,1835,Burg in Deutschland,610,Das Schloss Saaleck war eine im Mittelalter en...
5054,5054,Planung und Organisation,318,Das von Oliver Wight unter anderem entwickelte...
5377,5377,Literaturwissenschaft,2501,Frauenliteratur bezeichnet ein Genre sowohl be...
5648,5648,Alternative-Rock-Band,251,Chase Atlantic ist eine australische Alternati...
3971,3971,Soziologie,648,Erlebnisgesellschaft ist ein teils journalisti...

In [2]:
df.shape

(6942, 4)

In [3]:
df = df.drop(['id', 'category', 'length'], axis=1)

In [4]:
df

                                                   text
0     Tāmar und Schawqīya (arabisch تامر وشوقية, DMG...
1     Achtung: Streng geheim! (Originaltitel: Missio...
2     Alien Surfgirls ist eine australische Jugendse...
3     All Saints ist eine australische Fernsehserie ...
4     Alle lieben Diggy ist eine australische Zeiche...
...                                                 ...
6937  Weiche Daten ist eine wörtliche Lehnübersetzun...
6938  Als Wertermittlungsgebühr wird in Deutschland ...
6939  In Deutschland beschreibt der Begriff Widerruf...
6940  Das Zahlungsdiensteaufsichtsgesetz (ZAG) regel...
6941  Zahlungsort ist im Schuldrecht der Ort, an dem...

[6942 rows x 1 columns]

In [5]:
train=df.sample(frac=0.8,random_state=200) #random state is a seed value

test=df.drop(train.index)

In [6]:
train

                                                   text
367   Cactus ist ein Test-Framework, das von der Apa...
5931  Bedscha (auch Beja, Bedauye, Bedawi, Badawiyya...
36    H2O – Plötzlich Meerjungfrau (Originaltitel: H...
4275  Nachhaltigkeit in der Forstwirtschaft bezeichn...
3973  Die Freizeitgesellschaft ist eine vorhergesagt...
...                                                 ...
6357  Gustav Wasa ist eine Literatursatire von Cleme...
1988  Semen Jurijewitsch Holszański (* um 1450; † 15...
3526  Deadly Sting ist ein Best-of-Album der Scorpio...
3994  Die Raving Society (auch deutsch: Ravende Gese...
4707  Altenteil, Ausgedinge (Österreich) oder Austra...

[5554 rows x 1 columns]

In [8]:
train.to_csv('train.csv', index=False)

In [9]:
test

                                                   text
2     Alien Surfgirls ist eine australische Jugendse...
17    Cleverman ist eine australisch-US-amerikanisch...
18    The Code ist eine australische Fernsehserie vo...
37    The Heart Guy (dt. etwa der Herz-Typ, im Origi...
48    Lexi & Lottie – Detektive im Doppelpack ist ei...
...                                                 ...
6908  Sesame Credit ist ein Kredit-Scoring-System de...
6915  Stand-by-Kredit (englisch Stand-by facility) i...
6918  Tilgung nennt man im Finanzwesen die planmäßig...
6921  Kreditnehmern, die ein Damnum (= Disagio) in K...
6925  Überschuldung liegt vor, wenn das Vermögen ein...

[1388 rows x 1 columns]

In [10]:
test.to_csv(r'test.csv', index=False)